services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receivables-flow-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/app/data/production.db
      - JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret}
      - PORT=3000
    volumes:
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  sqlite_data:
    driver: local

networks:
  app-network:
    driver: bridge